"""add pipeline runs

Revision ID: 0bd7227ef16b
Revises: ae40e93de351
Create Date: 2026-09-17 18:50:09.827567

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0bd7227ef16b"
down_revision: Union[str, Sequence[str], None] = "ae40e93de351"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pipeline_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "success", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "jobs_fetched", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "active_jobs", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "eligible_jobs", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "rankings_persisted",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pipeline_runs")
    # ### end Alembic commands ###
