"""add job enrichments

Revision ID: 1944018518ef
Revises: 2294c14ef6fa
Create Date: 2026-09-18 11:26:36.426729

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1944018518ef"
down_revision: Union[str, Sequence[str], None] = "2294c14ef6fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_enrichments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("extractor_version", sa.String(length=100), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("minimum_experience_years", sa.Integer(), nullable=True),
        sa.Column("maximum_experience_years", sa.Integer(), nullable=True),
        sa.Column("seniority", sa.String(length=100), nullable=True),
        sa.Column("employment_type", sa.String(length=100), nullable=True),
        sa.Column("education", sa.Text(), nullable=True),
        sa.Column(
            "required_skills",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "preferred_skills",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "cloud_platforms",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "data_platforms",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "responsibilities",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "deal_breakers",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "extracted_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", name="uq_job_enrichment_job_id"),
    )
    op.create_index(
        op.f("ix_job_enrichments_content_hash"),
        "job_enrichments",
        ["content_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_enrichments_extractor_version"),
        "job_enrichments",
        ["extractor_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_enrichments_job_id"), "job_enrichments", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_job_enrichments_seniority"),
        "job_enrichments",
        ["seniority"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_job_enrichments_seniority"), table_name="job_enrichments")
    op.drop_index(op.f("ix_job_enrichments_job_id"), table_name="job_enrichments")
    op.drop_index(
        op.f("ix_job_enrichments_extractor_version"), table_name="job_enrichments"
    )
    op.drop_index(op.f("ix_job_enrichments_content_hash"), table_name="job_enrichments")
    op.drop_table("job_enrichments")
    # ### end Alembic commands ###
