"""add job gap analyses

Revision ID: 1a7ea6d25a03
Revises: 1944018518ef
Create Date: 2026-09-18 11:51:53.270408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a7ea6d25a03'
down_revision: Union[str, Sequence[str], None] = '1944018518ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_gap_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('profile_name', sa.String(length=100), nullable=False),
    sa.Column('analyzer_version', sa.String(length=100), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('matched_required_skills', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('missing_required_skills', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('matched_preferred_skills', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('missing_preferred_skills', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('matched_platforms', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('missing_platforms', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('deal_breakers', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('experience_fit', sa.String(length=50), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('experience_gap_years', sa.Float(), nullable=True),
    sa.Column('required_skill_match_ratio', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('preferred_skill_match_ratio', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('platform_match_ratio', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('gap_score', sa.Float(), nullable=False),
    sa.Column('fit_summary', sa.Text(), nullable=False),
    sa.Column('analysis_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'profile_name', name='uq_job_gap_analysis_job_profile')
    )
    op.create_index(op.f('ix_job_gap_analyses_analyzer_version'), 'job_gap_analyses', ['analyzer_version'], unique=False)
    op.create_index(op.f('ix_job_gap_analyses_content_hash'), 'job_gap_analyses', ['content_hash'], unique=False)
    op.create_index(op.f('ix_job_gap_analyses_experience_fit'), 'job_gap_analyses', ['experience_fit'], unique=False)
    op.create_index(op.f('ix_job_gap_analyses_gap_score'), 'job_gap_analyses', ['gap_score'], unique=False)
    op.create_index(op.f('ix_job_gap_analyses_job_id'), 'job_gap_analyses', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_gap_analyses_profile_name'), 'job_gap_analyses', ['profile_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_gap_analyses_profile_name'), table_name='job_gap_analyses')
    op.drop_index(op.f('ix_job_gap_analyses_job_id'), table_name='job_gap_analyses')
    op.drop_index(op.f('ix_job_gap_analyses_gap_score'), table_name='job_gap_analyses')
    op.drop_index(op.f('ix_job_gap_analyses_experience_fit'), table_name='job_gap_analyses')
    op.drop_index(op.f('ix_job_gap_analyses_content_hash'), table_name='job_gap_analyses')
    op.drop_index(op.f('ix_job_gap_analyses_analyzer_version'), table_name='job_gap_analyses')
    op.drop_table('job_gap_analyses')
    # ### end Alembic commands ###
