"""add ranking score components

Revision ID: 2294c14ef6fa
Revises: 5a749817b0c6
Create Date: 2026-09-18 00:31:32.588322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2294c14ef6fa'
down_revision: Union[str, Sequence[str], None] = '5a749817b0c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_rankings', sa.Column('deterministic_score', sa.Float(), nullable=True))
    op.add_column('job_rankings', sa.Column('semantic_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_rankings', 'semantic_score')
    op.drop_column('job_rankings', 'deterministic_score')
    # ### end Alembic commands ###
