"""add job rankings

Revision ID: 3fa47a073edc
Revises: f2439d1b3c99
Create Date: 2026-09-17 18:02:32.221662

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3fa47a073edc"
down_revision: Union[str, Sequence[str], None] = "f2439d1b3c99"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_rankings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("profile_name", sa.String(length=100), nullable=False),
        sa.Column("bucket", sa.String(length=50), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("rank_position", sa.Integer(), nullable=False),
        sa.Column(
            "ranked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_job_rankings_bucket"), "job_rankings", ["bucket"], unique=False
    )
    op.create_index(
        op.f("ix_job_rankings_job_id"), "job_rankings", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_job_rankings_profile_name"),
        "job_rankings",
        ["profile_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_rankings_ranked_at"), "job_rankings", ["ranked_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_job_rankings_ranked_at"), table_name="job_rankings")
    op.drop_index(op.f("ix_job_rankings_profile_name"), table_name="job_rankings")
    op.drop_index(op.f("ix_job_rankings_job_id"), table_name="job_rankings")
    op.drop_index(op.f("ix_job_rankings_bucket"), table_name="job_rankings")
    op.drop_table("job_rankings")
    # ### end Alembic commands ###
