"""add job embeddings

Revision ID: 5927248fe9e2
Revises: 7ff711c021ad
Create Date: 2026-09-17 23:01:18.890826

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = "5927248fe9e2"
down_revision: Union[str, Sequence[str], None] = "7ff711c021ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_embeddings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("model_name", sa.String(length=255), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "model_name", name="uq_job_embedding_job_model"),
    )
    op.create_index(
        op.f("ix_job_embeddings_content_hash"),
        "job_embeddings",
        ["content_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_embeddings_job_id"), "job_embeddings", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_job_embeddings_model_name"),
        "job_embeddings",
        ["model_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_job_embeddings_model_name"), table_name="job_embeddings")
    op.drop_index(op.f("ix_job_embeddings_job_id"), table_name="job_embeddings")
    op.drop_index(op.f("ix_job_embeddings_content_hash"), table_name="job_embeddings")
    op.drop_table("job_embeddings")
    # ### end Alembic commands ###
