"""add ranking gap score

Revision ID: 72ec62f126ed
Revises: 1a7ea6d25a03
Create Date: 2026-09-18 12:55:15.267609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72ec62f126ed'
down_revision: Union[str, Sequence[str], None] = '1a7ea6d25a03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_rankings', sa.Column('gap_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_rankings', 'gap_score')
    # ### end Alembic commands ###
