"""add company discovery candidates

Revision ID: 7ff711c021ad
Revises: 65cc32a6f174
Create Date: 2026-09-17 20:28:29.236332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ff711c021ad'
down_revision: Union[str, Sequence[str], None] = '65cc32a6f174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_discovery_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('discovered_ats', sa.String(length=50), nullable=True),
    sa.Column('discovered_identifier', sa.String(length=255), nullable=True),
    sa.Column('career_url', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name', name='uq_company_discovery_normalized_name')
    )
    op.create_index(op.f('ix_company_discovery_candidates_normalized_name'), 'company_discovery_candidates', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_company_discovery_candidates_status'), 'company_discovery_candidates', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_discovery_candidates_status'), table_name='company_discovery_candidates')
    op.drop_index(op.f('ix_company_discovery_candidates_normalized_name'), table_name='company_discovery_candidates')
    op.drop_table('company_discovery_candidates')
    # ### end Alembic commands ###
