"""add job application assets

Revision ID: 848895db4423
Revises: 72ec62f126ed
Create Date: 2026-09-18 15:50:39.034992

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "848895db4423"
down_revision: Union[str, Sequence[str], None] = "72ec62f126ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_application_assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("profile_name", sa.String(length=100), nullable=False),
        sa.Column("generator_version", sa.String(length=100), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("recruiter_dm", sa.Text(), nullable=False),
        sa.Column("email_subject", sa.Text(), nullable=False),
        sa.Column("email_body", sa.Text(), nullable=False),
        sa.Column("cover_note", sa.Text(), nullable=False),
        sa.Column("resume_summary", sa.Text(), nullable=False),
        sa.Column(
            "skills_to_emphasize",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "missing_skills_warning",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "resume_bullets_to_emphasize",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "interview_talking_points",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "generated_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "job_id", "profile_name", name="uq_job_application_asset_job_profile"
        ),
    )
    op.create_index(
        op.f("ix_job_application_assets_content_hash"),
        "job_application_assets",
        ["content_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_application_assets_generator_version"),
        "job_application_assets",
        ["generator_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_application_assets_job_id"),
        "job_application_assets",
        ["job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_application_assets_profile_name"),
        "job_application_assets",
        ["profile_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_job_application_assets_profile_name"),
        table_name="job_application_assets",
    )
    op.drop_index(
        op.f("ix_job_application_assets_job_id"), table_name="job_application_assets"
    )
    op.drop_index(
        op.f("ix_job_application_assets_generator_version"),
        table_name="job_application_assets",
    )
    op.drop_index(
        op.f("ix_job_application_assets_content_hash"),
        table_name="job_application_assets",
    )
    op.drop_table("job_application_assets")
    # ### end Alembic commands ###
