"""add job application states

Revision ID: ae40e93de351
Revises: 3fa47a073edc
Create Date: 2026-09-17 18:32:24.075872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae40e93de351'
down_revision: Union[str, Sequence[str], None] = '3fa47a073edc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_application_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('profile_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'new'"), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'profile_name', name='uq_job_application_state')
    )
    op.create_index(op.f('ix_job_application_states_job_id'), 'job_application_states', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_application_states_profile_name'), 'job_application_states', ['profile_name'], unique=False)
    op.create_index(op.f('ix_job_application_states_status'), 'job_application_states', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_application_states_status'), table_name='job_application_states')
    op.drop_index(op.f('ix_job_application_states_profile_name'), table_name='job_application_states')
    op.drop_index(op.f('ix_job_application_states_job_id'), table_name='job_application_states')
    op.drop_table('job_application_states')
    # ### end Alembic commands ###
