"""link rankings to pipeline runs

Revision ID: b3bdb3c07cad
Revises: 0bd7227ef16b
Create Date: 2026-09-17 19:20:28.291148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3bdb3c07cad'
down_revision: Union[str, Sequence[str], None] = '0bd7227ef16b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_rankings', sa.Column('pipeline_run_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_job_rankings_pipeline_run_id'), 'job_rankings', ['pipeline_run_id'], unique=False)
    op.create_foreign_key(None, 'job_rankings', 'pipeline_runs', ['pipeline_run_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'job_rankings', type_='foreignkey')
    op.drop_index(op.f('ix_job_rankings_pipeline_run_id'), table_name='job_rankings')
    op.drop_column('job_rankings', 'pipeline_run_id')
    # ### end Alembic commands ###
