"""add canonical job key

Revision ID: b3ea1ce7ee98
Revises: 15aa723dd3b0
Create Date: 2026-09-17 16:31:29.540227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3ea1ce7ee98'
down_revision: Union[str, Sequence[str], None] = '15aa723dd3b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('canonical_key', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_jobs_canonical_key'), 'jobs', ['canonical_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_canonical_key'), table_name='jobs')
    op.drop_column('jobs', 'canonical_key')
    # ### end Alembic commands ###
