const $=(id)=>document.getElementById(id);const status=(t)=>{$("status").textContent=t};
async function config(){return chrome.storage.local.get(["api","token"])}
async function activeTab(){const [tab]=await chrome.tabs.query({active:true,currentWindow:true});return tab}
async function call(path,options={}){const c=await config();if(!c.api||!c.token)throw new Error("Save API URL and companion token first.");const r=await fetch(c.api+path,{...options,headers:{"Content-Type":"application/json","X-JobIntel-Token":c.token,...(options.headers||{})}});if(!r.ok)throw new Error((await r.text())||`HTTP ${r.status}`);return r.json()}
function extractVisibleJob(){const text=(sels)=>{for(const s of sels){const e=document.querySelector(s);const v=e?.textContent?.trim();if(v)return v}return""};const h=location.hostname.toLowerCase();let portal="browser";if(h.includes("linkedin"))portal="linkedin";else if(h.includes("naukri"))portal="naukri";else if(h.includes("foundit"))portal="foundit";else if(h.includes("indeed"))portal="indeed";else if(h.includes("workday")||h.includes("myworkdayjobs"))portal="workday";const title=text(["h1",".job-details-jobs-unified-top-card__job-title","[data-testid='jobsearch-JobInfoHeader-title']"]);const company=text([".job-details-jobs-unified-top-card__company-name","[data-testid='inlineHeader-companyName']","[data-automation-id='jobPostingCompany']","a[href*='/company/']"]);const loc=text([".job-details-jobs-unified-top-card__primary-description-container","[data-testid='job-location']","[data-automation-id='locations']"]);const desc=text([".jobs-description__content","#jobDescriptionText","[data-automation-id='jobPostingDescription']","main"]);if(!title)throw new Error("Could not detect a visible job title on this page.");return{portal,title,company:company||"Unknown company",location:loc||null,description:desc?desc.slice(0,20000):null,url:location.href}}
function fillWorkday(answers){const mapping={first_name:[/first.?name/i],last_name:[/last.?name/i],email:[/email/i],phone:[/phone|mobile/i],current_location:[/address|location|city/i],linkedin_url:[/linkedin/i],github_url:[/github/i],portfolio_url:[/portfolio|website/i]};let filled=0;for(const el of [...document.querySelectorAll("input,textarea")]){if(el.value)continue;const id=el.id||"",name=el.name||"",aria=el.getAttribute("aria-label")||"",ph=el.getAttribute("placeholder")||"",label=id?document.querySelector(`label[for="${CSS.escape(id)}"]`)?.textContent||"":"",hay=`${id} ${name} ${aria} ${ph} ${label}`;for(const [key,patterns] of Object.entries(mapping)){const value=answers[key];if(!value||!patterns.some(p=>p.test(hay)))continue;el.focus();if(el instanceof HTMLTextAreaElement)Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,"value")?.set?.call(el,String(value));else Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value")?.set?.call(el,String(value));el.dispatchEvent(new Event("input",{bubbles:true}));el.dispatchEvent(new Event("change",{bubbles:true}));filled++;break}}return{filled}}
(async()=>{const c=await config();$("api").value=c.api||"https://api-production-a56fd.up.railway.app";$("token").value=c.token||""})();
$("save").addEventListener("click",async()=>{await chrome.storage.local.set({api:$("api").value.trim().replace(/\/$/,""),token:$("token").value.trim()});status("Connection saved locally.")});
$("capture").addEventListener("click",async()=>{try{status("Reading visible job…");const tab=await activeTab();const [{result}]=await chrome.scripting.executeScript({target:{tabId:tab.id},func:extractVisibleJob});const r=await call("/companion/capture",{method:"POST",body:JSON.stringify(result)});status(r.new?"Captured as a new job.":"Captured; matched existing job.")}catch(e){status(String(e.message||e))}});
$("autofill").addEventListener("click",async()=>{try{const tab=await activeTab();if(!/workday|myworkdayjobs/i.test(tab.url||""))throw new Error("Open a Workday application page first.");const p=await call("/companion/profile");const [{result}]=await chrome.scripting.executeScript({target:{tabId:tab.id},func:fillWorkday,args:[p.answers]});status(`Filled ${result.filled} field(s). Review manually; Submit is never clicked.`)}catch(e){status(String(e.message||e))}});
